version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: ecommerce-tax-calculator-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_tax_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce-tax-calculator-server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_tax_calculator
      DB_PORT: 5432
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce-tax-calculator-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 