version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: tax-calculator-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tax_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tax-calculator-server
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tax_calculator
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tax-calculator-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge